'use strict';
const token=new URL(location.href).searchParams.get('token');
const $=id=>document.getElementById(id);
let job, selected=new Set(), current, mode='number', zones={number:null,title:null}, drag=null, scanId=null, rows=[];
const api=async(url,options={})=>{const r=await fetch(url,{...options,headers:{'x-page-renamer-token':token,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;};
function status(s,error=false){$('zoneStatus').textContent=s;$('zoneStatus').className='status'+(error?' error':'');}
async function load(){try{job=await api('/api/manifest');$('jobName').textContent=job.job+' · '+job.pages.length+' pages';selected=new Set(job.pages.map(p=>p.id));current=job.pages.find(p=>p.image)?.id;renderPages();showPage();$('reviewPanel').hidden=true;}catch(e){$('jobName').textContent='Open a job in PlanSwift';status(e.message,true);}}
function renderPages(){const el=$('pageList');el.replaceChildren();for(const [i,p] of job.pages.entries()){const row=document.createElement('div');row.className='page'+(p.id===current?' selected':'');const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.has(p.id);cb.onchange=()=>{cb.checked?selected.add(p.id):selected.delete(p.id);count();};const b=document.createElement('b');b.textContent=String(i+1);const s=document.createElement('span');s.textContent=p.name+(p.image?'':' (no image)');row.append(cb,b,s);row.onclick=e=>{if(e.target===cb)return;current=p.id;renderPages();showPage();};el.append(row);}count();}
function count(){$('selectedCount').textContent=`${selected.size} selected`;}
function showPage(){const p=job?.pages.find(p=>p.id===current);if(!p)return;$('currentPage').textContent=p.name;const img=$('planImage');img.src=p.image?`/api/image/${encodeURIComponent(p.id)}?token=${token}`:'';img.onload=drawZones;img.onerror=()=>status('Could not show this page image.',true);drawZones();}
function imageRect(){return $('planImage').getBoundingClientRect();}
function drawZones(){document.querySelectorAll('.overlay').forEach(e=>e.remove());const b=$('imagebox').getBoundingClientRect(),r=imageRect();for(const [key,z] of Object.entries(zones)){if(!z)continue;const e=document.createElement('div');e.className='overlay '+key;e.style.left=(r.left-b.left+z.x*r.width)+'px';e.style.top=(r.top-b.top+z.y*r.height)+'px';e.style.width=(z.w*r.width)+'px';e.style.height=(z.h*r.height)+'px';$('imagebox').append(e);}}
function at(e){const r=imageRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
$('imagebox').addEventListener('pointerdown',e=>{if(!$('planImage').src)return;drag=at(e);$('imagebox').setPointerCapture(e.pointerId);});
$('imagebox').addEventListener('pointermove',e=>{if(!drag)return;const p=at(e);zones[mode]={x:Math.min(drag.x,p.x),y:Math.min(drag.y,p.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)};drawZones();});
$('imagebox').addEventListener('pointerup',e=>{if(!drag)return;const p=at(e);zones[mode]={x:Math.min(drag.x,p.x),y:Math.min(drag.y,p.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)};drag=null;if(zones[mode].w<.005||zones[mode].h<.005)zones[mode]=null;drawZones();status(zones.number?'Sheet number box ready. Draw a title box if you want titles.':'Draw the sheet number box.');});
function setMode(which){mode=which;$('numberBtn').classList.toggle('active',which==='number');$('titleBtn').classList.toggle('active',which==='title');}
$('numberBtn').onclick=()=>setMode('number');$('titleBtn').onclick=()=>setMode('title');$('clearBtn').onclick=()=>{zones={number:null,title:null};drawZones();};
$('selectAll').onclick=()=>{selected=new Set(job.pages.map(p=>p.id));renderPages();};$('selectNone').onclick=()=>{selected.clear();renderPages();};$('refresh').onclick=load;
$('undoBtn').onclick=async()=>{try{if(!confirm('Restore the page names from the last applied run for this job?'))return;const out=await api('/api/undo',{method:'POST',body:'{}'});await load();status(`Restored ${out.count} page names.`);}catch(e){status(e.message,true);}};
$('scanBtn').onclick=async()=>{const btn=$('scanBtn');try{if(!zones.number)throw Error('Draw the sheet number box first.');if(!selected.size)throw Error('Select at least one sheet.');btn.disabled=true;status(`Reading ${selected.size} sheets locally. This can take a few minutes…`);const out=await api('/api/scan',{method:'POST',body:JSON.stringify({ids:[...selected],numberZone:zones.number,titleZone:zones.title})});scanId=out.scanId;rows=out.results;renderReview();status('OCR finished. Review the names below.');$('reviewPanel').scrollIntoView({behavior:'smooth'});}catch(e){status(e.message,true);}finally{btn.disabled=false;}};
function renderReview(){const body=$('results');body.replaceChildren();$('reviewPanel').hidden=false;for(const r of rows){const tr=document.createElement('tr');const td=(content)=>{const e=document.createElement('td');if(content instanceof Node)e.append(content);else e.textContent=content;tr.append(e);return e;};const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!r.apply;cb.disabled=!!r.error;cb.onchange=()=>r.apply=cb.checked;td(cb);td(r.oldName||'—');td(r.number||'—');const inp=document.createElement('input');inp.type='text';inp.value=r.newName||'';inp.disabled=!!r.error;inp.oninput=()=>{r.newName=inp.value;};td(inp);td(r.error?'—':`${r.confidence}%`);const warning=td(r.error||r.warnings?.join('; ')||'Ready');warning.className=r.error||r.warnings?.length?'warn':'ok';body.append(tr);}const warn=rows.filter(r=>r.error||r.warnings?.length).length;$('summary').textContent=`${rows.length} scanned · ${rows.filter(r=>r.apply).length} ready to apply · ${warn} need review`;}
$('applyBtn').onclick=async()=>{const selectedRows=rows.filter(r=>r.apply&&!r.error).map(r=>({id:r.id,newName:r.newName}));const el=$('applyStatus');try{if(!selectedRows.length)throw Error('Check at least one row.');if(!confirm(`Apply ${selectedRows.length} page names in PlanSwift? Review the list before continuing.`))return;$('applyBtn').disabled=true;el.textContent='Checking pages in PlanSwift and applying names…';el.className='status';const out=await api('/api/apply',{method:'POST',body:JSON.stringify({scanId,entries:selectedRows})});el.textContent=`Renamed ${out.count} pages. Journal: ${out.journal}`;el.className='status success';await load();}catch(e){el.textContent=e.message;el.className='status error';}finally{$('applyBtn').disabled=false;}};
$('csvBtn').onclick=()=>{const escape=s=>'"'+String(s??'').replaceAll('"','""')+'"';const csv=['Current,Sheet Number,Proposed,Confidence,Warning',...rows.map(r=>[r.oldName,r.number,r.newName,r.confidence,r.error||r.warnings?.join('; ')].map(escape).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='PlanSwift-page-name-preview.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
new ResizeObserver(drawZones).observe($('imagebox'));load();
